const extensions = {
    css: ["file code", "css3 alternate", "orange", true],
    js: ["file code", "js", "yellow", true],
    php: ["file alternate", "php", "blue", true],
    py: ["file alternate", "python", "blue", true],
    scss: ["file code", "sass", "red", true],
    less: ["file code", "less", "red", true],
    rb: ["file alternate", "gem", "red", true],
    apk: ["file", "android", "green", false],
    exe: ["file", "windows", "blue", false],
    msi: ["file", "windows", "blue", false],
    db: ["file", "database", "blue", false],
    sqlite: ["file", "database", "blue", false],
    sqlite2: ["file", "database", "blue", false],
    sqlite3: ["file", "database", "blue", false],
    iso: ["file", "dot circle", "yellow", false],
    cpp: "file code",
    c: "file code",
    cc: "file code",
    html: "file code",
    txt: "file alternate",
    text: "file alternate",
    zip: "file archive",
    tar: "file archive",
    bz2: "file archive",
    wheel: ["file archive", "python", "blue"],
    xml: "file code",
    xlsx: "file excel",
    xlt: "file excel",
    xls: "file excel",
    csv: "file excel outline",
    pdf: "file pdf",
    ppt: "file powerpoint",
    pptx: "file powerpoint",
    mp3: "file audio",
};

export default extensions;
